import { TELEGRAM_HANDOFF_EXECUTION_EVENT_TYPES } from './handoff-execution.js';
import {
  TELEGRAM_REAL_PRESALE_HANDOFF_ATTEMPT_EVENT_TYPE,
  TELEGRAM_REAL_PRESALE_HANDOFF_RESULT_EVENT_TYPES,
} from './real-presale-handoff-orchestration.js';
import { TELEGRAM_MANUAL_FALLBACK_EVENT_TYPES } from './manual-fallback.js';
import { TELEGRAM_NOTIFICATION_DELIVERY_ATTEMPT_EVENT_TYPES } from './notification-delivery-attempts.js';
import { TELEGRAM_NOTIFICATION_INTENT_EVENT_TYPES } from './notification-intents.js';
import { TELEGRAM_SELLER_WORK_QUEUE_EVENT_TYPES } from './seller-work-queue.js';

export const TELEGRAM_EVENT_TYPES = Object.freeze([
  'SOURCE_ENTRY',
  'SOURCE_BOUND',
  'ATTRIBUTION_STARTED',
  'ATTRIBUTION_EXPIRED',
  'REQUEST_CREATED',
  TELEGRAM_SELLER_WORK_QUEUE_EVENT_TYPES.call_started,
  TELEGRAM_MANUAL_FALLBACK_EVENT_TYPES.call_started,
  TELEGRAM_MANUAL_FALLBACK_EVENT_TYPES.assigned_to_seller,
  'HOLD_STARTED',
  'HOLD_EXTENDED',
  'HOLD_EXPIRED',
  'GUEST_CANCELLED_BEFORE_PREPAYMENT',
  'GUEST_CANCELLED',
  'SELLER_NOT_REACHED',
  'PREPAYMENT_CONFIRMED',
  'HANDOFF_PREPARED',
  ...Object.values(TELEGRAM_HANDOFF_EXECUTION_EVENT_TYPES),
  TELEGRAM_REAL_PRESALE_HANDOFF_ATTEMPT_EVENT_TYPE,
  ...Object.values(TELEGRAM_REAL_PRESALE_HANDOFF_RESULT_EVENT_TYPES),
  ...Object.values(TELEGRAM_NOTIFICATION_INTENT_EVENT_TYPES),
  ...Object.values(TELEGRAM_NOTIFICATION_DELIVERY_ATTEMPT_EVENT_TYPES),
  'TICKET_SENT',
  'REMINDER_SENT',
  'BOARDING_SENT',
  'POST_TRIP_SENT',
  'REVIEW_SUBMITTED',
]);
