export const BOOKING_REQUEST_STATUSES = Object.freeze([
  'NEW',
  'ATTRIBUTED',
  'CONTACT_IN_PROGRESS',
  'HOLD_ACTIVE',
  'WAITING_PREPAYMENT',
  'PREPAYMENT_CONFIRMED',
  'CONFIRMED_TO_PRESALE',
  'GUEST_CANCELLED',
  'HOLD_EXPIRED',
  'SELLER_NOT_REACHED',
  'CLOSED_UNCONVERTED',
]);

export const BOOKING_HOLD_STATUSES = Object.freeze([
  'ACTIVE',
  'EXTENDED',
  'EXPIRED',
  'RELEASED',
  'CONVERTED',
  'CANCELLED',
]);

export const TELEGRAM_TICKET_STATUSES = Object.freeze([
  'REQUEST_RECEIVED',
  'AWAITING_SELLER_CONFIRMATION',
  'AWAITING_PREPAYMENT',
  'PAYMENT_CONFIRMED',
  'TICKET_READY',
  'REMINDER_SENT',
  'BOARDING_READY',
  'USED',
  'CANCELLED',
]);

export const TELEGRAM_NOTIFICATION_TYPES = Object.freeze([
  'REQUEST_RECEIVED',
  'SELLER_ASSIGNED',
  'HOLD_STARTED',
  'HOLD_EXTENDED',
  'HOLD_EXPIRING',
  'HOLD_EXPIRED',
  'PREPAYMENT_INSTRUCTIONS',
  'PAYMENT_CONFIRMED',
  'TICKET_SENT',
  'REMINDER_SENT',
  'BOARDING_SENT',
  'POST_TRIP_SENT',
  'REVIEW_REQUEST_SENT',
  'REVIEW_RECEIVED',
]);
